#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Jun 30 08:55:40 WEST 2023
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim devil_tb_behav -key {Behavioral:sim_1:Functional:devil_tb} -tclbatch devil_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/cris/Documents/0_Projects/MancusoCollab/devil-in-the-fpga/hardware/waves_DUT/devil_DUT.wcfg -log simulate.log"
xsim devil_tb_behav -key {Behavioral:sim_1:Functional:devil_tb} -tclbatch devil_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/cris/Documents/0_Projects/MancusoCollab/devil-in-the-fpga/hardware/waves_DUT/devil_DUT.wcfg -log simulate.log

